#!/bin/bash

IMAGE_NAME=${IMAGE_NAME:-"oanhnn/caddy:latest"}

echo "=> Building the image $IMAGE_NAME"
export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
       BUILD_VERSION=${IMAGE_NAME:13} \
       VCS_REF=`git rev-parse --short HEAD`

docker pull $IMAGE_NAME || true
docker build --cache-from $IMAGE_NAME \
             --compress \
             --label "org.label-schema.build-date=$BUILD_DATE" \
             --label "org.label-schema.name='The Caddy image'" \
             --label "org.label-schema.description='The tidy Caddy image'" \
             --label "org.label-schema.url='https://github.com/oanhnn/docker-caddy'" \
             --label "org.label-schema.vcs-url='https://github.com/oanhnn/docker-caddy.git'" \
             --label "org.label-schema.vcs-ref=$VCS_REF" \
             --label "org.label-schema.version=$BUILD_VERSION" \
             --label "org.label-schema.schema-version=1.0" \
             --pull \
             --tag $IMAGE_NAME .
